name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of AgentDock is affected?
      options:
        - Desktop App (Tauri)
        - Mobile App (Expo)
        - Provider - Codex
        - Provider - Claude Code
        - Provider - OpenCode
        - Core / Database
        - Contracts (TypeScript/Rust)
        - Build / CI
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "When I do X, I expect Y but instead I see Z..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: If applicable, add screenshots or log output to help explain your problem.
      placeholder: Paste logs between triple backticks

  - type: input
    id: version
    attributes:
      label: AgentDock Version
      description: What version of AgentDock are you running?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "macOS 14.0, Windows 11, Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
