name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of AgentDock would this feature affect?
      options:
        - Desktop App (Tauri)
        - Mobile App (Expo)
        - Provider - Codex
        - Provider - Claude Code
        - Provider - OpenCode
        - Core / Database
        - Contracts (TypeScript/Rust)
        - Build / CI
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: |
        Is your feature request related to a problem? If so, please describe.
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here.

  - type: checkboxes
    id: willing
    attributes:
      label: Would you be willing to submit a PR?
      description: This is absolutely not required, but we are happy to guide you in the contribution process.
      options:
        - label: Yes, I would like to submit a PR for this feature
          required: false
